ProjectFE/urls.py
from django.contrib import admin 
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 
from django.conf.urls import url 
from accounts import views as accounts_views
from articl import views as articl_views
from django.conf import settings
from ProjectFE import views
from home.views import HomeView
from django.contrib.auth.views import LoginView

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', HomeView.as_view(),name='home'),
    
    path(r'accounts/', include('accounts.urls', namespace='accounts' )),
    path(r'articl/', include('articl.urls', namespace='articl')),
    path(r'', include('home.urls', namespace='home')),
    
    path('register/', accounts_views.registerPage, name="register"),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', views.logout_view,name='logout'),
    #path('profile/',accounts_views.ProfileView, name='profile'),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT,}),
        ]

    

accounts/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.views import LoginView 

app_name = 'accounts'

urlpatterns = [
    path(r'', views.index, name="index"),
    path('register/', views.registerPage, name="register"),
    path('register/Details/', views.DetailsPage, name="Details"),
    path('login/', LoginView.as_view(),name='login'),
    path('profile/',views.ProfileView, name='profile'),
    url(r'^profile/(?P<pk>\d+)/$',views.ProfileView, name='profile_with_pk'),
    path('edit/',views.edit_profile, name='edit_profile'),

]

articl/urls.py
from django.conf.urls import url
from . import views 
from django.urls import path
from django.views.generic import ListView
from .models import ArticlPub

app_name = 'articl'

urlpatterns = [
    #path(r'', views.index, name='index'),
    path('postarticl/',views.createPost,name='postarticl'),
    path('listarticl/',views.listArticl,name='listArticl'),
    path('recommendation/',views.recommandation,name='recommandation'),
    path('<int:pk>/', views.deleteArticl,name='delele_Articl'),
    url(r'^detail/(?P<pk>\d+)/$',views.detail_articl, name='detail_articl'),
    url(r'(?P<pk>\d+)/Favourite/$',views.favourite, name='favourite'),
    path('favourites/',views.favourite_list,name='favourite_list'),
    path('<int:pk>/', views.moyenne,name='moyenne'),
    path('ajouterNote/<int:pk>/',views.ajouter_Note, name="ajouter_note"),
    path('livres_note/', views.list_note, name='list_note'),
    
    
    #path('search/',views.SearchResults, name='search_results'),
    #path('search/',views.Articl_Filtred_list, name='search'),
    #path('class/articl/', views.ArticlListView.as_view(),name='class_articlList'),


]

home/urls.py
from django.conf.urls import url
from . import views 
from django.urls import path
from .views import HomeView, change_followers

app_name = 'home'

urlpatterns = [
    path(r'', HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_followers, name='change_followers'),
    path('<int:pk>/', views.avr_fav,name='avr_fav'),
]

articl/models.py
from django.db import models
from accounts.models import Profile
from django.utils import timezone
import os
from django.conf import settings
from django.contrib.auth.models import User

class ArticlPub(models.Model):
    ArticlTYPE=(
      ('1','Research Article'),
      ('2','Research Paper'),
      ('3','Review Paper'),
      ('4','Review Article'),
      ('5','Peer-Reviewed Articles'),
    )
    
    DOMAINE=(
        #list of fields https://www.quora.com/What-are-different-fields-in-computer-science
        ('1','Computer Hardware'),
        ('2','Computer Networking'),
        ('3','Computer Software'),
        ('4','Cloud computing'),
        ('5','Cyber Security and Ethical Hacking'),
        ('6','Data Science and Data Analysis'),
        ('7','Programming Language'),
        ('8','Artificial intelligence'), 
        ('9','Operating system'),
        ('10','Web Development'),
        ('11','Web Designing'),
        ('12','Graphics design'),
        ('13','Network Analytics and testing'),
        ('14','Robotics'),
        ('15','others field'),

        )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    titre=models.CharField(max_length=500)
    resumé=models.CharField(max_length=2000, blank=True)
    keywords=models.CharField(max_length=500, blank=True)
    maison_ed=models.CharField(max_length=500,blank=True)
    typeArticl=models.CharField(max_length=100,blank=False,choices=ArticlTYPE)
    #published_date = models.DateField(null=True, blank=True)
    path=models.FileField(blank=True,null=True,upload_to='chapter/%Y/')
    auteurEcrit = models.ManyToManyField(Profile, blank=True, null=True)
    favourite = models.ManyToManyField(User,related_name='favourite', blank=True)
    timestamp = models.DateField(auto_now=False, auto_now_add=True)
    domaineArt=models.CharField(max_length=100,choices=DOMAINE,blank=False,default='Computer Software ')
    def __str__(self):
      return self.titre

    

    def delete(self, *args, **kwargs):
       self.path.delete()
       super().delete(*args, **kwargs)
    
    def get_avg_rating(self):
      notes = Note.objects.filter(articl=self)
      count = len(notes)
      if count == 0:
        return(0)
      
      sum = 0
      for nt in notes:
        sum += nt.note
      return (sum/count)


        
        
    


class Note(models.Model):
    note = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True, null=True)
    articl = models.ForeignKey(ArticlPub, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return self.articl.titre
         




class Favorite(models.Model):
    date = models.DateTimeField(auto_now_add=True, null=True)
    articl = models.ForeignKey(ArticlPub, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_favorite=models.BooleanField(default=False)

    def __str__(self):
      return self.articl.titre
    
    @classmethod
    def add_favorite(cls, current_user, new_fav):
        favorite, created = cls.objects.get_or_create(current_user=current_user)
        favorite.users.add(new_fav)
    


    #after any changes: python manage.py makemigrations //// python manage.py migrate

articl/forms.py
from django import forms
from .models import ArticlPub,Note,Favorite
from django.forms import ModelForm
from datetime import date



class Postform(forms.ModelForm):
    path= forms.FileField(required=True)
    
    class Meta:
        model = ArticlPub
        fields = [
            "titre",
            "resumé",
            "keywords",
            "maison_ed",
            "typeArticl",
            "domaineArt",
            "path",
            "auteurEcrit",
        ]

        widgets = {
            "titre":forms.TextInput(attrs={'class':'form-control',
                                    'placeholder':'Title...'}),
            "resumé":forms.Textarea(attrs={'class':'form-control',
                                    'placeholder':'abstract...'}),   
            "keywords":forms.TextInput(attrs={'class':'form-control',
                                    'placeholder':'Keywords...'}),
            "typeArticl":forms.Select(attrs={'class':'form-control',
                                    'placeholder':'Select articl type...'}),
            "maison_ed":forms.TextInput(attrs={'class':'form-control',
                                    'placeholder':'publishing house...'}),
            #"published_date":forms.DateInput(attrs={'class':'form-control',
            #                        'placeholder':'YYYY-MM-DD'}),
            "auteurEcrit":forms.SelectMultiple(attrs={'class':'form-control',
                                    'placeholder':'Please select authors ...'}),
                    
            'domaineArt':forms.Select(attrs={'class':'form-control',
                                    'placeholder':'Select your domaine interest...'}),
                    }

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ("note",)

class FaveForm(forms.ModelForm):
    class Meta:
        model = Favorite
        fields = ("is_favorite",)
        widgets ={"is_favorite":forms.BooleanField(label="check this")
        }





"""class EcritForm(forms.ModelForm):
    class Meta:
        model = Ecrit
        fields = [
            "auteurEcrit",
            "articlEcrit",
            "ordreAuteur",
            ]"""

"""class SearchForm(forms.ModelForm):

    class Meta:
         model = ArticlPub
         fields = ['titre','keywords','resumé']"""

articl/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.conf import settings
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.views.generic import TemplateView, ListView , FormView
from .forms import Postform,NoteForm,FaveForm
from django.contrib import messages
from django.db.models import F,Aggregate,Avg
from django.contrib.auth.decorators import login_required
from django.forms.formsets import formset_factory
from django.core.files.storage import FileSystemStorage
from .models import ArticlPub,Note,Favorite
from accounts import views
from django.contrib.auth.models import User
from django.template.context import RequestContext
from .recommender import get_predict_list, demographic, get_ratings_vector
from accounts.models import Profile
from home.models import Follower

# Create your views here.
def index(request):
    return render(request ,'base.html')

@login_required
def detail_articl(request,pk):
    articl=ArticlPub.objects.get(pk=pk)
    notes=Note.objects.filter(articl=pk)
    
    average=notes.aggregate(Avg("note"))['note__avg']
    if average==None:
        average=0
    average=(round(average,2))
    

    is_favourite=False
    if articl.favourite.filter(pk=request.user.pk).exists():
        is_favourite=True

    #is_rated=False
    #if Note.user.filter(articl=pk,pk=request.user.pk).exists():
     #  is_rated=True
     
    context={'articl':articl,
            'notes':notes,
            'average':average,
            'is_favourite':is_favourite,
            #'is_rated':is_rated
            }
    return render(request,'detailArticl.html',context)

@login_required
def favourite_list(request):
    user= request.user
    favourite_articls=user.favourite.all()
    context={
        'favourite_articls':favourite_articls,
    }
    return render(request,'favourite_list.html',context)

@login_required
def createPost(request):
     # if not request.user.is_authenticated():
    #    raise Http404
    if request.method == 'POST':    
        form = Postform(request.POST, request.FILES )
        if form.is_valid() :
            ArticlPub =form.save(commit=False)
            ArticlPub.user=request.user
            ArticlPub.titre=form.cleaned_data.get('titre')
            ArticlPub.resumé=form.cleaned_data.get('resumé')
            ArticlPub.keywords=form.cleaned_data.get('keywords')
            ArticlPub.maison_ed=form.cleaned_data.get('maison_ed')
            ArticlPub.typeArticl=form.cleaned_data.get('typeArticl')
            ArticlPub.published_date=form.cleaned_data.get('published_date')
            ArticlPub.path=form.cleaned_data.get('path')
            

            ArticlPub.save()
            form.save_m2m()

            print('post created')
            messages.add_message(request, messages.SUCCESS , "You have posted your articl successfully" )
            return redirect('home:home')
    else:
        form=Postform()        
        
    context = {'form':form}
    return render(request,"PostArticl.html",context)


@login_required
def deleteArticl(request,pk):
    
    if request.method == 'POST':
        articl=ArticlPub.objects.get_or_create(pk=pk)
        articl.delete()
    return  redirect('articl:listArticl')

def add_f(request,pk):
    fav_art=ArticlPub.objects.get(pk=pk)    
    Favorite.add_favorite(request.user, new_favorite) 
    return redirect('ListArticl.html')

@login_required
def listArticl(request):
    
    artPubs=ArticlPub.objects.all().order_by("-timestamp")
    notes=Note.objects.all()
    context = {'artPubs':artPubs,'notes':notes}
    return render(request,"ListArticl.html",context)

def favourite(request,pk):
    articl=get_object_or_404(ArticlPub,pk=pk)
    if articl.favourite.filter(pk=request.user.pk).exists():
        articl.favourite.remove(request.user)
        print('remove to fav')
    else:
        articl.favourite.add(request.user)
        print('add to fav')

    #return HttpResponseRedirect(articl.get_absolute_url())
    return redirect('articl:favourite_list')

@login_required
class ArticlListView(ListView):
    model = ArticlPub
    template_name = 'article/listé.html'
    context_object_name = 'articlpubs'

@login_required
def ajouter_Note(request, pk):

    articl = ArticlPub.objects.get(pk=pk)
    note=Note.objects.all()
    user=request.user.id
    if Note.objects.filter(user=user,articl=articl).exists():
        Note.objects.filter(user=user,articl=articl).delete()
        if request.method == "POST":
            form = NoteForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.note=request.POST["note"]
                data.user=request.user
                data.articl= articl
                data.save()
                print('note ajouter')
                return redirect('articl:listArticl')
        else:
            form = NoteForm()

    else:
    
        if request.method == "POST":
            form = NoteForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.note=request.POST["note"]
                data.user=request.user
                data.articl= articl
                data.save()
                print('note ajouter')
                return redirect('articl:listArticl')
        else:
            form = NoteForm()
    
        
         
    return render(request, 'ListArticl.html', {"form": form})



def saveInfos(request):
    user = User.objects.get(username=request.POST["user"])
    articl = ArticlPub.objects.get(id=request.POST["articl"])
    note = Note.objects.filter(user=user, articl=articl)
    if note:
        user_note = Note.objects.get(user=user, articl=articl)
        user_note.note = request.POST["note"]
        user_note.save()
    else:
        user_note = Note(articl=articl, user=user, note=request.POST["note"])
        user_note.save()


def list_note(request):
    notes = Note.objects.filter(user=request.user)
    if request.POST:
        saveInfos(request, request.POST["type"])

    context={
        'notes':notes
    }
    return render(request,'liste_note.html',context)

def ajouter_(request, pk):

    articl = ArticlPub.objects.get(pk=pk)
    if request.method == "POST":
        form = NoteForm(request.POST or None)
        if form.is_valid():
            data = form.save(commit=False)
            data.note=form.cleaned_data.get('note')
            data.user=request.user
            data.articl=articl
            data.save()
            print('note ajouter')
            return redirect('articl:listArticl')
    else:
        form = NoteForm()
    return render(request, 'ListArticl.html', {"form": form})



def moyenne(request,pk):
    if request.method == 'POST':
        notes=Note.objects.all().filter(articl=pk)
        average=Note.objects.all().aggregate(Avg("note"))['note__avg']
        print(average)
        context={}
        return render(request,'ListArticl.html',context)

    
def favorite(request,pk):
    user = User.objects.get(id=request.POST["user"])
    articl = ArticlPub.objects.get(id=request.POST["articl"])
    in_favorite=Favorite.objects.filter(user=user,articl=articl)
    if in_favorite:
        instance = Favoris.objects.get(user=user, livre=livre)
        instance.delete()
    else:
        instance = Favoris(livre=livre, user=user)
        instance.save()
    
    return render(request,'recommandation/list_favoris.html',context)


@login_required 
def recommandation(request):
    profiles=Profile.objects.exclude(id=request.user.id)
    users = User.objects.exclude(id=request.user.id) 
    arts=ArticlPub.objects.all() 
        
    follower, created = Follower.objects.get_or_create(current_user=request.user)
    followers = follower.users.all()
    predict_list = get_predict_list(request.user)
    print(predict_list)
        #rec=User.objects.filter(pk__in=predict_list)
    #second start
    demographic_list = demographic(request.user)
    print(demographic_list)
        
    for item in demographic_list.keys():
            if item not in predict_list:
                predict_list.append(item)
        
        
    rec=User.objects.filter(pk__in=predict_list)

    articlList = []
    for value in predict_list:
            #art=ArticlPub.objects.filter(user=value)
            articlList.append(value)
        
        
    articls=ArticlPub.objects.filter(user__id__in=articlList) #get articles where user__id is __in the list articlList
    print(articlList) 
        #second end

    context = {'profiles':profiles,
        'arts':arts,
        'users':users,
        'followers':followers,
        'articls':articls,
        'rec':rec}    
    return render(request,'recommend.html',context)

#malware 
    
        
#intro 
#opensll
#intro géné

articl/templates/ListArticl.html
{%  extends 'base.html' %}
{% load static %}
{%  block content %}
<h2>List of articls</h2>

    
    <p>
      <a href="{% url 'articl:postarticl' %}" class="btn btn-primary">Upload Articl</a>
    </p>
    

  <table class="table mb-0">
    <thead>
      <tr>

      </tr>
      <tr>
        
        <th>Title</th>
        <th>Posted by</th>
        <th>Download</th>
        <th>Noter</th>
        <th>Note</th>
        <th>Favorite</th>
        <th>Delete</th>
        
      </tr>
    </thead>
    <tbody>
      {% for artPub in artPubs %}
        <tr>
            <td>{{artPub.titre}} </td>
            <td>{{artPub.user}} </td>
            <td><a href="{{artPub.path.url}}" class="btn btn-primary btn-sm" target="_blank"> Open pdf </a>
            </td>
            <td>
              <form action=" {% url 'articl:ajouter_note' artPub.pk %} "  method="POST" >
                {% csrf_token %}
                <label for="note">Rating</label>
                <input type="text" name="note" class="form-control" >
                <br>
                <input type="submit" class="btn btn-danger" value="ajouter note" >

              </form>
              
            </td>
    
              {%for note in notes%}
                {% if note.user == request.user %}
                  {%if artPub.pk == note.articl.pk %}
                    <td>{{note.note}} <br> {{note.user}}</td>
                    

                  {%endif%}
                {%endif%}
              {% endfor %}
              <td>
                <a href=" {% url 'articl:favourite'  pk=artPub.pk  %} ">
                  <button type="button" class="btn btn-success">fav</button>
                  
                </a>
              </td>
            {% if artPub.user == request.user %}
              <td>
                <form method="POST" action="{% url 'articl:delele_Articl' pk=artPub.pk  %} ">
                  {% csrf_token %}
                  <button type="submit" class="btn-danger btn-sm">Delete </button>
                   
                </form>
              </td>
            {% endif %}

            
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

articl/templates/detailArticl.html
{%  extends 'base.html' %}
{% load static %}
{%  block content %}
<style>
  #open{
    width: 30%;
    max-width: 100%;
    height: auto;
    border:5px ;
    padding-bottom: 1rem;
    margin-right: 1rem;
    
}
#fav{
    width: 50%;
    max-width: 100%;
    height: auto;
    border:5px ;
    padding-top:2rem;
}

</style>
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Post Content Column -->
    <div class="col-lg-8">

      <!-- Title -->
      
      <h1 class="mt-4"> {{articl.titre}}</h1>
      
      <!-- Author -->
      <p class="lead">
        by
        <a href="{%  url 'accounts:profile_with_pk' pk=articl.user.pk  %}">{{articl.user}}</a>
      </p>

      <hr>

      <!-- Date/Time -->
        <footer class="blockquote-footer">
          <cite >Posted on  {{articl.timestamp}}</cite>
        </footer>
      
      <hr>
      <h4>Abstract</h4>
      <p class="mb-0">{{articl.resumé}}</p>
      <hr>
    </div>
       <!-- Sidebar Widgets Column -->
       <div class="col-md-4">

        <!-- Search Widget -->
        
        <div class="card my-4">
          
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
  
                <a href="{{articl.path.url}}" class="btn" target="_blank"><h4>Open</h4> <img src="{% static 'image/pdf2.png' %}" alt="" id="open" class="ml-3" title="open" ></a>
              
  
              </div>
              <div class="col-lg-6">
                
                {% if is_favourite %}
                <a href=" {% url 'articl:favourite'  pk=articl.pk  %} ">
                  <img src="{% static 'image/bookmark4.png' %}" alt="" id="fav" class="ml-3" title="Saved" >
          
                </a>
                {% else %}
                <a href=" {% url 'articl:favourite'  pk=articl.pk  %} ">
                  <img src="{% static 'image/bookmark3.png' %}" alt="" id="fav" class="ml-3" title="Save me" >
                </a>
                {% endif %}
  
  
              </div>
            </div>
          </div>
        </div>
            
        

        <!-- Categories Widget -->
        <div class="card my-4">
          <h4 class="card-header">Rate this Article</h4>
          
          <div class="card-body">
          <form action=" {% url 'articl:ajouter_note' articl.pk %} "  method="POST" >
            {% csrf_token %}
            <label for="note"><h3 class="ml-3">Rating</h3></label>
            
            <input type="range" name="note" id="rangeInpute" min="0" max="5" step="1" value="0" oninput="amount.value-rangeInpute.value">
            <output name="amount" id="amount" for="rangeInpute">0</output>
            <br>
            <input type="submit" class="btn btn-danger" value="ajouter note" >
            
      
          </form>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h4 class="card-header">Average </h4>
          <div class="card-body">
            <label for="note"><h3 class="ml-3">{{average}}/5</h3></label>
          </div>
        </div>

      </div>
      <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-6">

              <div class="str_Rating_detail">         
                <!--star rating-->
                <div id="" data-rating="3" data-rateyo-read-only="false" class="rateYo bookrating" ></div>  
                <!-- to show selected star value-->                     <input type="text" class="bookrating"> 
                <!--to store rating name and language -->               <input type="hidden" class="bookId" value="17">
                                
                </div>

                


            </div>
          </div>
        </div>
      </div>


    </div>
<table class="table mb-0">
  <h3> {{articl.titre}}</h3>
  <thead>
    <tr>
      <th>Created by</th>
      <th>Created on</th>
      <th>Read it</th>
      <th>add Rating</th>
      <th>Average Rating</th>
      <th>Fav section</th>
    </tr>
  </thead>
  
  <tbody>
      
      <tr>
          <td>{{articl.user}} </td>
          <td>{{articl.timestamp}} </td>
          <td><a href="{{articl.path.url}}" class="btn btn-primary btn-sm" target="_blank"> Open pdf </a></td>
          <td>
            <form action=" {% url 'articl:ajouter_note' articl.pk %} "  method="POST" >
              {% csrf_token %}
              <label for="note"><h3>Rating</h3></label>
              
              <input type="range" name="note" id="rangeInpute" min="0" max="5" step="1" value="0" oninput="amount.value-rangeInpute.value">
              <output name="amount" id="amount" for="rangeInpute">0</output>
              <br>
              <input type="submit" class="btn btn-danger" value="ajouter note" >
              
        
            </form>
          </td>
          <td>{{average}}</td>
          <td><div id="favourite-section"> 
            {% if is_favourite %}
                <a href=" {% url 'articl:favourite'  pk=articl.pk  %} ">
                  <img src="{% static 'image/bookmark4.png' %}" alt="" id="fav" class="ml-3" title="Saved" >
           
                </a>
            {% else %}
            <a href=" {% url 'articl:favourite'  pk=articl.pk  %} ">
              <img src="{% static 'image/bookmark3.png' %}" alt="" id="fav" class="ml-3" title="Save me" >
            </a>
            {% endif %}
        </div></td>
      </tr>
    
  </tbody>
</table>
{% endblock %}

articl/templates/recommend.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
<style>
  #add {
    width: 10%;
    max-width: 100%;
    height: auto;
    border:5px ;
    padding-bottom: 1rem;
}
#fav{
    width: 5%;
    max-width: 100%;
    height: auto;
    border:5px ;
    padding-top:2rem;
}



#content{
  background-color:whitesmoke;
  border-radius: 2rem;
  text-transform: uppercase;
  transition: background-color 650ms;
  
  
}
#tooltip {
  position: relative;
  display: inline-block;
  
}

.one{
  cap
}

.tooltip .tooltiptext {
  visibility: hidden;
  width: 120px;
  background-color: black;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px 0;

  /* Position the tooltip */
  position: absolute;
  z-index: 1;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
}
</style>
<!-- Page Content -->
<div class="container">

  <div class="row">

    <!-- Blog Entries Column -->

    <div class="col-md-8">
      <div class="main-message">
        <div class="cta">
            
        </div>
      </div>

      <!-- Blog Post -->
      {% for obj in articls %}
      
     
      <div class="card mb-4" style="border-radius: 2rem">
        <div class="card-body">
          
          <a href=" {% url 'articl:detail_articl' pk=obj.pk %} "> <h2 class="card-title" title="Learn more">{{obj.titre}}  </h2> </a>
     
          <div class="text"><p class="one">{{obj.resumé}}</p></div>
          <div class = "content-dir-item" >
            <a href="{{obj.path.url}}" class="btn " id="but" target="_blank">Read More &rarr;</a>
            
              <a href=" {% url 'articl:favourite'  pk=obj.pk  %} ">
                <img src="{% static 'image/bookmark3.png' %}" alt="" id="fav" class="ml-3" title="Save me" >
              </a>
          </div>
          
        </div>
        <div class="card-footer text-muted">
          {{obj.timestamp}} Posted by
          <a href="{%  url 'accounts:profile_with_pk' pk=user.pk  %}"> {{obj.user}}</a>
        </div>
      </div>
      {% endfor %}

      

      <!-- Pagination -->
      <ul class="pagination justify-content-center mb-4">
        <li class="page-item">
          <a class="page-link" href="#">&larr; Older</a>
        </li>
        <li class="page-item disabled">
          <a class="page-link" href="#">Newer &rarr;</a>
        </li>
      </ul>

    </div>

    <!-- Sidebar Widgets Column -->
    <div class="col-md-4">

      <!-- Side Widget -->
      <div class="card my-4" id="content" >
        <h4 class="card-header" >RECOMMENDATIONS</h4>
        <div class="card-body">
            {% for obj in articls %}
              <a href=" {% url 'articl:detail_articl' pk=obj.pk %} "> <h5 class="card-title" title="Learn more">{{obj.titre}}  </h5> </a>
            {% endfor %}  
          </div>
      </div>
      <!-- Categories Widget -->
     
      <div class="card my-4" id="content" >
        <h4 class="card-header">recommended profiles</h4>
        <div class="card-body">
              {% for p in rec %}
                {% if not p in followers %}
                <div class = "content-dir-item">
                    <a href=" {% url 'home:change_followers' operation='add' pk=p.pk  %} ">
                    <img src="{% static 'image/add.png' %}" alt="" id="add" class="ml-3" title="Follow" ></a>
                    <a href="{%  url 'accounts:profile_with_pk' pk=p.pk  %}" >{{  p }}</a>
                </div>
              {% endif %}
              {% endfor %} 

            </div>
      </div>
      
      <div class="card my-4" id="content" >
        <h4 class="card-header" >Other people</h4>
        <div class="card-body">
            {% for user in users %}
              {% if not user in followers %}
              <div class = "content-dir-item">
                  <a href=" {% url 'home:change_followers' operation='add' pk=user.pk  %} ">
                  <img src="{% static 'image/add.png' %}" alt="" id="add" class="ml-3" title="Follow" ></a>
                  <a href="{%  url 'accounts:profile_with_pk' pk=user.pk  %}" >{{  user.username }}</a>
              </div>
              {% endif %}
            {% endfor %}  
          </div>
      </div>
      <div class="card my-4" id="content" >
        <h4 class="card-header" > followers list</h4>
        <div class="card-body">
        {% for follower in followers %}
              <div class = "content-dir-item">
                <a href=" {% url 'home:change_followers' operation='remove' pk=follower.pk  %} ">
                  <img src="{% static 'image/follower.png' %}" alt="" id="add" class="ml-3" title="Unfollow" ></a>
                </a>
                <a href="{%  url 'accounts:profile_with_pk' pk=follower.pk  %}">{{  follower.username }}</a>
                
              </div>
       {% endfor %}
      </div>
      </div>

    </div>

  </div>
  <!-- /.row -->

</div>
<!-- /.container -->
{% endblock %}

articl/templates/search.html
{% extends 'base.html' %}


{% block content %}
<h1>Search Results</h1>
<form action="post">
    {% csrf_token %}
    {{form}}
    <input class="btn btn-primary" type="submit" value="Search"/>
</form>



{% endblock %}