ProjectFE/urls.py
from django.contrib import admin 
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve 
from django.conf.urls import url 
from accounts import views as accounts_views
from articl import views as articl_views
from django.conf import settings
from ProjectFE import views
from home.views import HomeView
from django.contrib.auth.views import LoginView

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', HomeView.as_view(),name='home'),
    
    path(r'accounts/', include('accounts.urls', namespace='accounts' )),
    path(r'articl/', include('articl.urls', namespace='articl')),
    path(r'', include('home.urls', namespace='home')),
    
    path('register/', accounts_views.registerPage, name="register"),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path('login/', LoginView.as_view(),name='login'),
    path('logout/', views.logout_view,name='logout'),
    #path('profile/',accounts_views.ProfileView, name='profile'),
    
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT,}),
        ]

    

accounts/urls.py
from django.urls import path
from . import views 
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.views import LoginView 

app_name = 'accounts'

urlpatterns = [
    path(r'', views.index, name="index"),
    path('register/', views.registerPage, name="register"),
    path('register/Details/', views.DetailsPage, name="Details"),
    path('login/', LoginView.as_view(),name='login'),
    path('profile/',views.ProfileView, name='profile'),
    url(r'^profile/(?P<pk>\d+)/$',views.ProfileView, name='profile_with_pk'),
    path('edit/',views.edit_profile, name='edit_profile'),

]

articl/urls.py
from django.conf.urls import url
from . import views 
from django.urls import path
from django.views.generic import ListView
from .models import ArticlPub

app_name = 'articl'

urlpatterns = [
    #path(r'', views.index, name='index'),
    path('postarticl/',views.createPost,name='postarticl'),
    path('listarticl/',views.listArticl,name='listArticl'),
    path('recommendation/',views.recommandation,name='recommandation'),
    path('<int:pk>/', views.deleteArticl,name='delele_Articl'),
    url(r'^detail/(?P<pk>\d+)/$',views.detail_articl, name='detail_articl'),
    url(r'(?P<pk>\d+)/Favourite/$',views.favourite, name='favourite'),
    path('favourites/',views.favourite_list,name='favourite_list'),
    path('<int:pk>/', views.moyenne,name='moyenne'),
    path('ajouterNote/<int:pk>/',views.ajouter_Note, name="ajouter_note"),
    path('livres_note/', views.list_note, name='list_note'),
    
    
    #path('search/',views.SearchResults, name='search_results'),
    #path('search/',views.Articl_Filtred_list, name='search'),
    #path('class/articl/', views.ArticlListView.as_view(),name='class_articlList'),


]

home/urls.py
from django.conf.urls import url
from . import views 
from django.urls import path
from .views import HomeView, change_followers

app_name = 'home'

urlpatterns = [
    path(r'', HomeView.as_view(),name='home'),
    url(r'^connect/(?P<operation>.+)/(?P<pk>\d+)/$',views.change_followers, name='change_followers'),
    path('<int:pk>/', views.avr_fav,name='avr_fav'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Home</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <!--Ion Icons-->
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Aldrich&display=swap" rel="stylesheet">
    <!--Our own stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"  >
</head>
<body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    {% if user.is_authenticated %}
    <header>
        <div class="container">
            <nav>
                    <div class="nav-brand">
                        <a href="{%  url 'home:home'  %}">
                            <img src="{% static 'image/logo.png' %}" alt="" >
                        </a>
                    </div>
                    <div class="menu-icons open">
                        <i class="icon ion-md-menu"></i>
                    </div>
                    
                    <ul class="nav-list">
                            <div class="menu-icons close">
                                <i class="icon ion-md-close">Home</i>
                            </div>
                            <li class="nav-item">
                                <a class="nav-link" href="{%  url 'home:home'  %}">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{%  url 'articl:recommandation'  %}">RECOMMENDATIONS</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{%  url 'articl:postarticl'  %}"> Add an article </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{%  url 'articl:favourite_list'  %}"> Favourite list</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                  {{user.username}}
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" href="{%  url 'accounts:profile'  %}"> Profile </a>
                                  <a class="dropdown-item" href="{%  url 'accounts:edit_profile'  %}"> Edit Profile </a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="{%  url 'password_change'  %}">Change password</a>
                                  <a class="dropdown-item" href="{%  url 'logout'  %}">Log out</a>
                                  
                                </div>
                              </li>
                            
                        
                    </ul>
            </nav>
            
        </div>
    </header>
    <section class="hero">
        <div class="contaider">
            
        </div>   
    </section>
        
    
   {% endif %}
   
    <section class="experience">
        <div class="container">
            {% if user.is_authenticated %}
            <!--<div class="main-message">
                <div class="cta">
                    <a href="{%  url 'articl:postarticl'  %}" class="btn"><h3> add your article </h3></a>
                </div>
            </div>-->
            
            
            
            {% endif %}    
            
            {% block content %}
    
            {% endblock %}
            
         </div>
         
         
    </section>
    <div class="footer ">
        <div class="footer-content">
            <p >Copyright &copy; Projet Licence 2019-2020</p>
        </div>
    </div>
   
    
    
    <script  src="{% static 'js/scripts.js' %}"></script>
</body>
</html> 

templates/base2.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,user-scalable=no, initial-scale=1, shrink-to-fit=no maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Title</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <!--Ion Icons-->
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Aldrich&display=swap" rel="stylesheet">
    <!--Our own stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"  >
  </head>
  <body>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    <script type="text/javascript" src="scripts.js"></script>

    <header>
      <div class="container">
        <nav>
          <div class="container">
           {% if user.is_authenticated %}
           <div class="nav-brand">
            <a href="{%  url 'home:home'  %}">
                <img src="{% static 'image/logo.png' %}" alt="" >
            </a>
          </div>
          <div class="menu-icons open">
            <i class="icon ion-md-menu"></i>
          </div>
          {% endif %}
           
       </nav>
      </div>

    </header>
   
    
        <div class="container">
          {% if user.is_authenticated %}
            <a href="{%  url 'home:home'  %}"> Home //</a>
              <a href="{%  url 'articl:postarticl'  %}"> Add an articl //</a>
              <a href="{%  url 'articl:listArticl'  %}"> List of articls //</a>
              <a href="{%  url 'articl:favourite_list'  %}"> Favourite list//</a>
              <a href="{%  url 'password_change'  %}"> Change password //</a>
              <a href="{%  url 'logout'  %}"> Log out// </a>
              <strong>  You are logged in as {{user.first_name}} {{user.last_name}} </strong>
          {% else %} 
              <a href="{%  url 'register'  %}"> Registration </a> 
              <a href="{%  url 'login'  %}"> Log in </a>
          {% endif %}    
          <hr> 
          {% block content %}
  
          {% endblock %}
       </div>
      
  </body>
</html>

templates/firstpage.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <!--Ion Icons-->
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <!--Google Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Nunito&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Aldrich&display=swap" rel="stylesheet">
    <!--Our own stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"  >
</head>
<body>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    
    <header>
        <div class="container">
            <nav>
                    
                    <ul class="nav-list"> 
                            <li class="nav-item">
                                <a href="{%  url 'login'  %}" class="btnt" > Registration </a> 
                            </li>
                            <li class="nav-item">
                                <a href="{%  url 'register'  %}" class="btnt" > Registration </a> 
                            </li>
                    </ul>
            </nav>
        </div>
    </header>
  
        
    
   
   
    <section class="experience">
        
    </section>
    
    <footer class="py-5 bg-dark">
        <div class="container">
          <p class="m-0 text-center text-white">Copyright &copy; Projet Licence 2019-2020</p>
        </div>
        <!-- /.container -->
    </footer>
    
    <script  src="{% static 'js/scripts.js' %}"></script>
</body>
</html> 

templates/profile.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
    


<div class="container target">
    <div class="row">
        <div class="col-sm-10">
            <h1> Profile </h1>
          <br>
        </div>
      
    </div>
  <br>
    <div class="row">
        <div class="col-sm-3">
            <!--left col-->
            <ul class="list-group">
                <li class="list-group-item text-muted" contenteditable="false">Profile</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="">Joined</strong></span> 2.13.2014</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="">Last seen</strong></span> Yesterday</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Real name</strong></span> Joseph
                        Doe</li>
              <li class="list-group-item text-right"><span class="pull-left"><strong class="">Role: </strong></span> Pet Sitter
               
                      </li>
            </ul>
           <div class="panel panel-default">
             <div class="panel-heading">Insured / Bonded?

                </div>
                <div class="panel-body"><i style="color:green" class="fa fa-check-square"></i> Yes, I am insured and bonded.

                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Website <i class="fa fa-link fa-1x"></i>

                </div>
                <div class="panel-body"><a href="http://bootply.com" class="">bootply.com</a>

                </div>
            </div>
          
            <ul class="list-group">
                <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i>

                </li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="">Shares</strong></span> 125</li>
                <li class="list-group-item text-right"><span class="pull-left"><strong class="">Likes</strong></span> 13</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Posts</strong></span> 37</li>
                        <li class="list-group-item text-right"><span class="pull-left"><strong class="">Followers</strong></span> 78</li>
            </ul>
            <div class="panel panel-default">
                <div class="panel-heading">Social Media</div>
                <div class="panel-body">	<i class="fa fa-facebook fa-2x"></i>  <i class="fa fa-github fa-2x"></i> 
                    <i class="fa fa-twitter fa-2x"></i> <i class="fa fa-pinterest fa-2x"></i>  <i class="fa fa-google-plus fa-2x"></i>

                </div>
            </div>
        </div>
        <!--/col-3-->
        <div class="col-md-8">
            <div class="main-message">
              <div class="cta">
                  
              </div>
            </div>
            
            <!-- Blog Post -->
            {% for art in arts %}
            <div class="card mb-4" style="border-radius: 2rem">
              <div class="card-body">
                
                <a href=" {% url 'articl:detail_articl' pk=art.pk %} "> <h2 class="card-title" title="Learn more">{{art.titre}}  </h2> </a>
                <div class="text"><p class="one">{{art.resumé}}</p></div>
                <div class = "content-dir-item" >
                  <a href="{{art.path.url}}" class="btn " id="but" target="_blank">Read More &rarr;</a>
                  
                  <a href=" {% url 'articl:favourite'  pk=art.pk  %} ">
                      <img src="{% static 'image/bookmark3.png' %}" alt="" id="fav" class="ml-3" title="Save me" >
                  </a>
                  
                  <img src="{% static 'image/star.png' %}" alt="" id="fav" class="ml-3" title="avg rating" > 
                  <b> {{art.get_avg_rating}}</b>
                </div>
                
              </div>
              <div class="card-footer text-muted">
                {{art.timestamp}} Posted by
                <a href="{%  url 'accounts:profile_with_pk' pk=user.pk  %}"> {{art.user}}</a>
              </div>
            </div>
            {% endfor %}
      
            
      
            <!-- Pagination -->
            <ul class="pagination justify-content-center mb-4">
              <li class="page-item">
                <a class="page-link" href="#">&larr; Older</a>
              </li>
              <li class="page-item disabled">
                <a class="page-link" href="#">Newer &rarr;</a>
              </li>
            </ul>
      
          </div>
              
    </div>
           <div class="panel panel-default">
                <div class="panel-heading">Starfox221's Bio</div>
                <div class="panel-body"> A long description about me.

                </div>
</div></div>


            <div id="push"></div>
        </div>




    <p>  Welcome to my site {{user.username}} </p> 
    
    <li> first name :<i>{{user.first_name}}</i></li>
    <li> last name :<i>{{user.last_name}}</i></li>
    <li> birth date :<i>{{user.profile.birth_date}}</i></li>
    <li> domaine :<i>{{user.profile.domaine.value }}</i></li>

{% endblock %}

templates/upload.html
{%  extends 'base.html' %}
{% load static %}
{% block content %}
    <h1> Upload</h1>
   
{% endblock %}